### ISSUE TITLE
System Call은 무엇이며 무엇을위해 쓰일까요?

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/os-hardware#1]
질문: System Call은 무엇인가요? 없다면 어떤불편함이 생기는걸까요?
설명해주세요

**Comment by this-is-spear** [comment]
1. 커널 기반의 운영체제에서 하드웨어를 접근하거나 프로세스관련 기능을 처리하기 위해서는 시스템 콜을 통해 커널 처리를 호출합니다.
2. 만약에 시스템 콜이 없으면 사용자 모드에서 아무것도 할 수 없게 됩니다.  그래픽 출력이라거나 파일 다루는 등 행위도 커널의 도움으로 이루어지기 때문에 화면으로 출력하는 처리 등 입출력 처리, 하드웨어 제어 처리 등 모든 처리가 불가능해집니다.

**Comment by LudyPark** [comment]
![image](https://user-images.githubusercontent.com/78838791/174520490-cf353949-e0f8-4a33-939f-1786b3955aab.png)


#### 사용자 모드와 커널 모드

- 사용자 모드에서 실행되는 코드는 할 수 있는 일이 제한된다.
   - 예를 들어 프로세스가 사용자 모드에서 실행 중이면 디스크 입출력 요청을 할 수 없도록 설정한다.
- 커널 모드는 사용자 모드와 대비되는 모드로서 운영체제의 중요한 코드들이 실행된다.
   - 이 모드에서 실행되는 코드는 모든 특수한 명령어를 포함하여 원하는 모든 작업을 수행할 수 있다.
- 이 때 사용자 프로세스가 디스크를 읽기와 같은 특수 명령어를 실행해야 한다면 이런 제한 작업의 실행을 허용하기 위해 시스템 콜을 사용한다.

#### 시스템콜 이란?

- 시스템 콜은 OS와 사용자 프로그램을 이어주는 인터페이스 역할을 한다
- 유저 어플리케이션은 유저 모드에서 시스템콜 인터페이스를 호출하면 시스템콜은 커널모드에서 하드웨어에 접근하여 작업 후 어플리케이션에 반환한다.
 - 메모리의 특정 주소 범위에는 어떤 동작들이 할당되어 있다 (인터럽트 서비스 루틴). 이것을 가리키는 메모리 주소를 모아놓은 것을 시스템 콜 테이블(System call table)이라고 부르며, 인터럽트 벡터(Interrupt vector)라고도 부른다.

#### 시스템콜 호출 시 동작 과정

- 시스템 콜을 실행하기 위해 프로그램은 trap 특수 명령어를 실행하고 이 명령어는 커널 안으로 분기하는 동시에 특권 수준을 커널 모드로 상향 조정한다.
- 커널 모드로 진입하면 운영체제는 모든 명령어를 실행할 수 있고 이를 통해 프로세스가 요청한 작업을 수행한다.
- 완료되면 운영체제는 treturn-from-trap 특수 명령어를 호출하여 특권 수준을 사용자 모드로 다시 하향 조정하면서 호출한 사용자 프로그램으로 리턴한다.

#### 시스템 콜의 분류

- 프로세스 제어: end, abort, load, execute
- 파일 관리: create, delete, open, close, read, write
- 장치 관리: read, write, request, release
- 정보 유지: get/set time or date
- 통신: send/receive messages, transfer status
- 보호


#### 시스템콜이 없다면?

- 시스템콜이 없다면 즉 하드웨어에 대한 접근 권한이 유저에게 주어진다면 
![image](https://user-images.githubusercontent.com/78838791/178202574-4831852b-4b97-4d42-b2b8-8cedb4409448.png)

   운영체제가 프로그램을 실행하기 시작할 때 프로세스 목록에 해당 프로세스 항목을 만들고 메모리를 할당하며 프로그램 코드를 디스크에서 탑재하고 진입점 (예, main() 루틴 혹은 유사한 무엇)을 찾아 그 지점으로 분기하여 사용자 코드를 실행을 시작해야한다.

#### 그에 따른 문제점

- 프로그램을 하드웨어 CPU에서 직접 실행시키게 되면 프로세스가 특수한 종류의 연산(디스크 입출력 요청, CPU 또는 메모리와 같은 시스템 자원에 대한 추가 할당 요청 등 )을 수행하고자 할 때 프로세스는 시스템에 대한 권한이 없기 때문에 이러한 연산을 수행할 수 없어 문제가 발생한다.

**Comment by youngreal** [comment]
시스템 콜

**운영체제가 커널에 접근하기위한 인터페이스, 유저프로그램이 운영체제의 서비스를 받기위해 커널 함수를 호출할때 쓰게되는 기능**

운영체제별로 다르지만, 운영체제별로 사용가능하게된 서비스에대한 인터페이스를 제공한다

하드웨어를 직접 접근해야한다거나, 등등 엄청나게 여러이유로 시스템콜이 사용되며 
프로그래머들은 주로 시스템콜을 직접 호출하지않고 API를 통해 호출한다. 

(이유는 호환성 때문이다 시스템마다 어떤 시스템콜은  실행이 될수도있고 안될수도있다 , 또한 어렵다)

```
cp a.txt b.txt
(a.txt 를 b.txt에 복사한다)
```

위의 경우  modebit(사용자모드인지 커널모드인지 알리는 flag)가 커널모드로 설정되고 
커널모드로 들어가서 파일을 복사하고 다시 유저모드로 돌아가 로직을 마저 실행하게 된다
시스템콜이 있기때문에 저 명령어 한줄만으로 파일을 복사할수있는것이다 

시스템콜이 없다면?
OS별로 파일을 복사하는 것을 따로 정의 해주어야한다 (추상화 되어있기때문에 우리는 OS신경쓰지않고 개발이 가능했던 것)

**Comment by LudyPark** [comment]
#### 모드 비트 추가 설명

모드 비트가 커널모드 (1)이라면 CPU의 모든 메모리 영역에 접근 가능하지만 유저 모드(0)이라면 모든 메모리에 접근은 불가능하고 자신의 Address Space만 접근 가능하다. 

또한 커널모드일 경우 모든 instruction이나 op-code를 수행할 수 있지만 유저모드일 경우 I/O instruction이나 special register accesses(스택 포인터나 프로그램 카운터와 같은 특별한 레지스터의 값을 읽는 행위)와 관련된 instruction은 금지된다.

![image](https://user-images.githubusercontent.com/78838791/176114508-efd6c3d6-ce15-4f7b-a6be-9a44fd351a82.png)

- CPU와 메모리 사이에 MMU 하드웨어는 CPU에서 메모리로 가는 address 정보를 조사한다.
- 조사에 통과하면 Instruction Fetch 즉 instruction을 가져온다. instruction의 구조는 op-code와 operands로 구성된다. op-code를 통해 어떤 연산인지 확인한다.
- op-code(명령어)를 확인 후 만약  privileged op-code(I/O와 같은 중요한 역할을 하는 실행)을 시도하려 한다라고 판단되면 CPU를 운영체제로부터 박탈당한다.

> 모드 비트가 유저모드일 때, CPU가 접근하는 메모리 주소가 실행 중인 프로그램의 범위 밖이거나 I/O instruction등의 금지된 실행을 하려고 한다면 CPU를 운영체제로부터 박탈당한다. 
> 반대로 커널모드였을 경우는 위에서 언급한 검증 절차를 전혀 밟지 않아도 된다.

**Comment by youngreal** [comment]
모드비트에 대한 추가설명까지 좋습니다 ㅎㅎ 스터디시간에 이부분 가볍게 이야기해보고 더 이야기 할거없으면 close하겠습니다
