### ISSUE TITLE
deadlock

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/os-hardware#11]
1. 교착상태(deadlock)란 무엇인가요?
2. 교착상태의 발생조건에대해 이야기해주세요
3. 교착상태를 깨기위한 가장좋은 방법은 무엇인가요
4. 기아상태란?

**Comment by lee-ji-hoon** [comment]
## 1. 교착 상태(Deadlock)란 무엇인가요?
교착상태란 일련의 프로세스들이 서로가 가진 자원을 기다리며 block된 상태입니다.  
이렇게 말로만 하면 헷갈리니 그림으로 보면 아래와 같습니다.

<html>
<img src="https://user-images.githubusercontent.com/53300830/179128670-a1593b4f-b993-462a-8222-22202402d7ab.png" width="200" height="200"/>
</html>
신호등이 없는 상태에서 서로 가고자 하는 방향으로만 가는 도로의 상태를 교착 상태라고도 볼 수 있습니다.

## 2. 교착 상태의 발생 조건에 대해 이야기 해주세요
> 4가지 조건이 필요합니다.

### 1) 상호 배제 조건 (mutual exclusion condition)
- 매 순간 하나의 프로세스만이 자원을 사용할 수 있음
### 2) 점유와 대기 조건 (hold and wait condition)
- 프로세스는 자원을 스스로 내어놓을 뿐 강제로 빼앗기지 않음
### 3) 비선점 조건 (nopreemption condition)
- 자원을 가진 프로세스가 다른 자원을 기다릴 때 보유 자원을 놓지 않고 계속 가지고 있음
### 4) 순환 대기 조건 (circular-wait condition)
- 자원을 기다리는 프로세스 간에 사이클이 형성되어야 함.
- 프로세스 P0, P1, ... , Pn이 있을 때
    - P0은 P1이 가진 자원을 기다림.
    - P1은 P2가 가진 자원을 기다림.
    - P(n-1)은 Pn이 가진 자원을 기다림.
    - Pn은 P0이 가진 자원을 기다림.

## 3. 교착 상태를 깨기 위한 가장 좋은 방법은 무엇인가요?
> 우선 교착상태를 깨기 위한 방법을 우선 이야기 해보면서 어떤 방법이 좋은지부터 보면 좋을 것 같습니다.  
> 주로 4가지 처리 방법이 존재하는데 아래와 같습니다.
### 1) Deadlock Prevention (데드락 예방)
- 자원 할당 시 데드락의 4가지 필요 조건 중 어느 하나가 만족되지 않도록 하는 것
### 2) Deadlock Avoidance (데드락 회피)
- 자원 요청에 대한 부가적인 정보를 이용해서 데드락의 가능성이 없는 경우에만 자원을 할당
- 시스템 상태가 원래 상태로 돌아올 수 있는 경우에만 자원 할당
### 3) Deadlock Detection and recovery (데드락 탐지 및 회복)
- 데드락 발생은 허용하되, 그에 대한 탐지 루틴을 두어 데드락 발견시 회복
### 4) Deadlock Ignore (데드락 무시)
- 데드락을 시스템이 책임지지 않음
- UNIX를 포함한 대부분의 OS가 채택

_이러한 처리 방법 중에서는 현대에서는 대부분이 데드락을 무시합니다.
데드락 자체가 매우 드물게 발생하기 때문입니다.
언제 일어날지도 모르는 것을 예방하기 위해서 많은 오버헤드를 들이는 것이 비효율적이라고 판단했기에 데드락을 미연에 방지하지 않고 무시하는 것을 대부분의 OS에서 채택을 했습니다._
>추가적으로 이 부분은 다들 어떻게 생각하시는지 궁금하네요.  
개인적으로 찾아보면서 하고 있는데, _무엇이 최선이다_ 라고 확신이 생기지가 않네요. 개인적으로는 탐지 및 회복과 무시가 최선으로 보이긴합니다!

### 그럼 무시를 할 때는 시스템이 책임지지 않는데 발생하면 어떻게하지??
> 무시를 하기로 결정했다면 데드락 발생시 사용자가 시스템을 재부팅하거나 프로세스를 죽이는 방법으로 데드락을 해결을 해야합니다
## 4. 기아 상태란?
> 프로세스가 작업을 수행하지 못하고 무한히 기다리는 상태. (교착 상태와 다릅니다.)  
- 현실적으로 수행할 수 있는 작업이지만, 무기한 연기로 인해 수행할 수 없는 상태에 빠지는 것.
- 프로세스의 우선순위에 따라 자원을 할당할 경우, 우선순위가 낮은 프로세스들은 기아 상태에 빠질 수 있다.
- 기아 상태를 해결하기 위한 방안으로는 에이징(aging)이 있다.
- 어떤 자원을 오래 대기할수록, 해당 프로세스의 우선순위를 높여주는 방법이다.

### 참고
[이화여자대학교 - 반효경 교수님 강의(Deadlock 1 && 2)](https://core.ewha.ac.kr/publicview/C0101020140411151510275738?vmode=f)
[우아한 테크 - 10분 테크톡(🥁둔덩의 교착상태)](https://www.youtube.com/watch?v=FXzBRD3CPlQ&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9CTech)

**Comment by this-is-spear** [comment]
### 1. 교착상태(deadlock)란 무엇인가요?

교착 상태는 두 개 이상의 프로세스들이 서로 가진 자원을 기다리며 중단된 상태를 말합니다.

### 2. 교착상태의 발생조건에대해 이야기해주세요

**상호 배제 상황**

한 프로세스가 자원을 독점하고 있으며 다른 프로세스들은 접근이 불가능합니다.

**점유 대기 상황**

특정 프로세스가 점유한 자원을 다른 프로세스가 요청하는 상태입니다.

**비선점 상황**

다른 프로세스의 자원을 강제적으로 가져올 수 없습니다.

**화형 대기 상황**

프로세스 A는 프로세스 B의 자원을 요구하고 프로세스 B는 프로세스 A의 자원을 요구하는 등의 서로가 서로의 자원을 요구하는 상황을 말합니다.

### 3. 교착상태를 깨기위한 가장좋은 방법은 무엇인가요

1. 자원을 할당할 때 애초에 조건이 성립되지 않도록 설계합니다.
2. 교착 상태 가능성이 없을 때만 자원이 할당되며 프로세스당 요청할 자원들의 최대치를 통해 자원 할당 가능 여부를 파악하는 은행원 알고리즘을 사용합니다.
3. 교착 상태가 발생하면 교착 상태가 발생하게 된 사이클을 찾아보고 관련된 프로세스를 하나씩 지워봅니다.
4. 교착 상태는 매우 드물게 일어나기 때문에 이를 처리하는 비용이 더 커서 교착 상태가 발생하면 작업을 종료하는 방법도 있습니다.

> 응행원 알고리즘
>  응행원 알고리즘은 총 자원의 양과 현재 할당한 자원의 양을 기준으로 안정 또는 불안정 상태로 나누고 안정 상태로 가도록 자원을 할당하는 알고리즘입니다.

**Comment by LudyPark** [comment]
### 교착상태(deadlock)란?

- 스레드가 한정된 자원에 대해 경쟁할 때 자기가 원하는 자원을 남이 사용하고 있을 경우 자신이 쓸 수 있을 때까지 대기한다.
- 이 때 남이 계속 사용하고 있으면 자신은 무한정 기다려야하는 상황이 일어나는데 이를 deadlock이라고 한다.

### 교착상태의 발생조건

밑의 네 가지 조건을 모두 반족해야 데드락이 발생한다.

- **상호배제**
   - 최소한 한 자원은 반드시 공유 불가 상태여야한다.
   - 즉 한 순간에 한 스레드만 해당 자원을 사용할 수 있다.
   - 다른 스레드가 자원을 요청할 경우 자원이 반납될 때까지 그 스레드는 대기한다. 
- **붙잡고 기다리기**
   - 스레드는 반드시 한 자원을 붙잡은 상태에서 다른 스레드가 현재 붙잡고 있는 추가적인 자원을 얻기 위해 대기해야한다.
- **비선점**
   - 자원은 선점될 수 없다. 즉 스레드는 작업을 마무리 후 스스로 반납해야 한다. 
- **순환 대기**
   - 대기 중인 스레드 집합이 서로의 자원을 기다려야한다.
   - T0 , T1, ... Tn 개의 스레드가 있을 경우 T0는 T1이 붙잡고 있는 자원을 기다리고 Tn-1은 Tn이 붙잡고 있는 자원을 기다리고 Tn은 T0가 붙잡고 있는 자원을 기다린다.

### 교착 상태 해결 방법
- **예방** : 교착 상태를 발생하지 않도록한다
- **회피** : 교착 상태를 피한다.
- **복구** : 교착 상태에 빠지도록 두었다가 후에 조치한다.

#### 예방 기법

**Comment by youngreal** [comment]
## 교착상태(deadlock)란 무엇인가요?

한스레드가 특정 자원에대해 요청했을때 그 자원을 사용할수없는 상황이 발생하여 대기상태로 들어가고  이 대기상태에서 상태를 변경시킬수없는 상황을 교착상태라고 한다

## 교착상태의 발생조건에대해 이야기해주세요

상호배제 : 한번에 한 스레드만이 특정 자원을 사용할수있으며 ,다른스레드가 자원을 요청하면 
요청스레드는 자원이 방출될때까지 반드시 지연되어야 한다

점유-대기 : 스레드는 최소한 하나의 자원을 점유한채, 다른스레드에 의해 점유된 자원을 추가로 얻기위해선 반드시 대기해야한다

비선점 : 점유하고있는 스레드가 작업이 끝나야만 방출될수있다

순환 대기 : 스레드의 집합이있을때 자원을 대기하는 프로세스가 따로 존재한다


## 교착상태를 깨기위한 가장좋은 방법은 무엇인가요

### 교착상태 예방 : 교착상태가 발생하는 필요조건중 하나를 성립되지않도록 보장하는 방법

상호배제 : 상호배제 조건을 성립하지않게끔 하는방법을 불가능하다. 
근본적으로 공유할수없는 자원도 있기때문이다.

점유대기 : 점유대기를 보장하지않게되면 자원이 할당되어도 장기간 사용되지않을수 있는 가능성이 생겨 자원 이용률이 낮아질수있다.

비선점 :  CPU레지스터, DB 트랜잭션처럼 상태가 쉽게 저장되고 복원될수있는 자원에 종종 적용되며 뮤텍스락, 세마포어 같은 자원에는 적용될수없다.  교착상태가 가장 흔하게 발생하는 자원유형인 뮤텍스락, 세마포어에 사용할수없기때문에 일반적인 방법은 아니다

**순환대기**  : 가장 실용적인 해결책, 각 자원유형에 고유의 정수번호를 부여해(순서에 대한 표시)  해결하는방법ㅂ

**교착상태 예방하는 방법은  장치의 이용률이 저하되고 시스템 총처리율이 감소할수있다는 단점이있습니다**

### 교착상태 회피 : 스레드가 요구할 자원에대한 부가적인 정보를 미리 제공하여 운영체제가 각 요청을 위해 스레드에게 기다려야할지 않을지를 결정할수있게끔 하는방법
가장 유용한 모델중 하나가 각 스레드가 자신이 필요로 하는 각 유형의 자원마다 최대 수를 선언하도록 하는것이다. 
(은행원 알고리즘, 자원할당 그래프 알고리즘 등이 이런모델)

### 교착상태 탐지 :  교착상태가 발생했는지 시스템의 상태를 검사하는 알고리즘, 교착상태로부터 회복하는 알고리즘을 반드시 지원해야만 사용할수있는 방법 
=> 탐지, 회복하는 알고리즘을 실행시키는것 자체가  알고리즘 실행시간, 교착상태로부터 회복할때 손실이 생길수도있다는 가능성을 염두해야한다


## 기아상태란?

컴퓨터 자원들이 프로세스에의해 선점되지 못하는상황
