### ISSUE TITLE
질문!

### ISSUE THREAD

**Issue by heetae96** [Stacked-Book/os-hardware#12]
page, 책내용: 1장 23페이지에 종류가 같은 디바이스는 같은 인터페이스로 조작
질문: 리눅스는 디바이스의 종류가 같으면 같은 인터페이스로 조작하도록 되어있습니다. 이 말은 다른 os에서는 디바이스의 종류가 다르다면 안된다는 말같은데 기존의 윈도우 같은 경우에는 같은 디바이스면 따로 디바이스 드라이버 추가 설치가 필요없지않나요?

**Comment by youngreal** [comment]
22페이지 
- **리눅스뿐만아니라 OS에대해서도 설명할 내용은 많지만 간단히 설명하고자 둘을 크게 구별짓지 않겠습니다**

- **리눅스같은 OS가 없으면 그림 1-4 와 같이 여러개의 프로세스가 각각 디바이스를 조작하는 코드를 작성해야한다**

라는 부분을 토대로 저는 그 부분에서 리눅스 라기보다는 **리눅스같은 OS**라고 이해했습니다
즉 , 책에서 설명하는 리눅스는 리눅스만의 특징을 설명한다기보다 OS자체를 기준으로 설명하는것 같습니다 


p.s. 어떤경로로 들어오게되셨는지 궁금하네요 ㅎㅎ

**Comment by heetae96** [comment]
오 감사합니다. 이 책을 보면서 지금 운영체제에 대해서 공부 중 인데 혹시 저보다 더 공부 잘하시는 분들은 어떻게 공부하시는지 또는 어떤 것을 중점으로 보시는지 궁금해서 찾아보다 보니깐 여기 까지 왔습니다!
