### ISSUE TITLE
가상메모리

### ISSUE THREAD

**Issue by this-is-spear** [Stacked-Book/os-hardware#13]
### 질문

1. 가상 메모리란 무엇인가요?
2. 가상 메모리를 사용했을 때 장점이 있을까요? 
3. 이와 반대로 가상 메모리를 사용했을 때 단점이 있을까요? 

--- 

### 추가 질문

> 가상 메모리는 실제 메모리와 보조 기억 장치의 Swap 영역으로 구성된다.

JVM을 통해 클래스 파일을 실행하게 되면 Swap 영역을 설정하지 않으면 OOM이 발생합니다. 하지만 Swap 영역을 사용하게 되면 지연이 발생하기 때문에, 가급적 해당 영역을 사용하지 않도록 설계하는 것이 중요한데, 아래 내용들이 궁금해졌습니다. 

1. Swap 영역을 설정해야 하는 이유
2. Swap 영역을 사용하게 되면 지연이 발생하는 이유
3. Swap 영역을 사용하지 않도록 설계하는 방법은 무엇인지

**Comment by lee-ji-hoon** [comment]
## ❓ 가상 메모리란?
> 주기억장치의 부족한 물리적 저장공간을 보조기억장치를 이용해서 가상으로 늘려 주는 기술입니다.
- 물리적인 메모리 공간의 한계를 극복하기 위해 물리적인 메모리 공간만큼의 가상의 메모리공간을 확보하여 메모리 용량을 늘리는 기술입니다.
- 가상 메모리는 하드 디스크의 용량을 떼서 사용하는 기술인데, 페이지(Page) 단위로 하드디스크-램을 swap하면서 이뤄집니다.
## ✅ 가상 메모리 장점
### 메모리 크기의 제약으로부터 자유로워진다.
> 사용자 프로그램이 물리 메모리보다 커져도 실행이 가능하다는 의미입니다.

### 병행성 및 CPU 이용률 증가
> 사용자 프로그램이 더 작은 메모리를 차지하므로 더 많은 프로그램을 동시에 수행 가능합니다.  
> 그리고 주기억장치의 용량이 확대된 것처럼 프로그램이 실행 가능합니다.

## ✅ 가상 메모리 단점
### 전반적인 속도가 느려질 수 있습니다.
> 가상메모리를 사용할 경우 물리 메모리로 프로그램을 구동하는 것 보다 속도가 느려집니다.

### 싱글 페이지 관리기술일때보다 테이블의 수와 여러 페이지들을 핸들링하기위한 오버헤드가 증가합니다.
> 즉 간단하게 말하면 유저가 신경써야할 것들이 많아진다는 의미입니다.

## 📋 추가 내용
### 기법
1. **페이징(Paging)** 
   - 가상기억장치의 일반적인 구현 방법에는 프로그램을 고정된 크기의 일정한 블록으로 나누는 방식  

2. **세그멘테이션(Segmentation)**
   - 가변적인 크기의 블록으로 나누는 방식

### 요구 페이징(Demand Paging)
> 프로세스가 동작하면서 실제 필요로하는 부분만 메모리로 올리는 작업
- 현재 진행중인 프로그램의 작업 내용을 기억하기 위해 디스크 공간을 메모리처럼 활용 -> paging file, swap file이라고 한다.
- 어플리케이션 관점에서는 RAM의 크기가 증가한 것과 같은 효과를 가져온다.

### page
> 가상 메모리를 사용하는 최소 크기 단위
- paging file 에서 물리 메모리로 데이터를 로드할 때 아무 위치에나 나누어서 로드할 수 있도록 운영체제가 나눈 메모리 분할의 최소 크기이다.
- 인위적 연속성 : 가상 공간의 연속적 주소가 실제 물리적인 공간 상에서 연속일 필요가 없다.
- 필요 page에 접근하려면 결국 가상 메모리 주소에 대응하는 물리 메모리 주소를 찾아내야 한다.
   - page table을 통해 얻어온다!
![image](https://user-images.githubusercontent.com/53300830/185566300-5cfefae8-86c1-4d0b-8a9c-f6b0a77fabf0.png)

1. 페이징 하드웨어는 page table을 보고 page fault이면, 즉 물리 메모리에 없으면 OS에게 trap으로 알린다.
2. OS는 물리 메모리에 실제로 없는 것인지 잘못된 접근인지 확인한 후 잘못된 접근이었으면 종료한다.
3. empty frame(free page)을 얻는다.
4. page(요구페이지)를 frame(물리적 메모리 공간의 최소 단위, page와 같은 크기)으로 swap한다.
5. 프로세스의 page table과 TLB를 page-in & page-out 된 것을 토대로 수정한다.
6. page fault를 야기했던 명령부터 다시 실행한다.

### 가상메모리 사용 이유
> 일반적으로 시스템의 여러 프로세스들은 CPU와 메인 메모리를 공유해서 사용합니다.
- CPU를 공유하는 부분에 대해서는 일반적으로 순서를 기다리느라 단지 느려질 뿐이고 심각한 오류는 보통 발생하지 않습니다.
- 그러나 프로세스들이 존재하는 메모리의 여유가 없어 지나치게 많은 요구에 의해 오염될 경우 프로그램의 논리와 무관하게 오류가 생깁니다.
- 이러한 오류를 방지하기 위해서 나온 기술이 가상메모리 입니다.

### 주요기능
1. 주기억장치의 효율적 관리
   - 하드디스크를 주기억장치에 대한 캐시로 설정하여, 당장 사용하는 영역만 유지하고 쓰지 않는 데이터는 하드디스크로 옮긴다.
   - 필요할 때만 렘에 데이터를 불러와 올리고 다시 사용하지 않으면 하드디스크로 내림으로써 램을 효과적으로 관리한다.
2. 메모리 관리의 단순화
   - 각 프로세스마다 가상메모리의 통일된 주소 공간을 배정할 수 있으므로 메모리 관리가 단순해진다.
3. 메모리 용량 및 안전성 보장
   - 한정된 공간의 램이 아닌 거의 무한한 가상 메모리 공간을 배정함으로써 프로세스들끼리 메모리 침범이 일어날 여지를 크게 줄인다.

>  그렇다고해서 가상 메모리의 공간이 완전히 무한하다고 볼수는 없다.
일반적으로 가상 메모리의 권장 처음 크기는, 시스템에 설치된 물리적인 메모리의 1.5배이고, 가상 메모리의 권장 최대 크기는, 시스템에 설치된 물리적인 메모리의 3배 입니다.  
많은 메모리가 필요한 프로그램을 정기적으로 사용하는 경우에는 페이징 파일의 크기를 늘릴 수 있지만, 보통의 경우에는 페이징 파일의 크기를 권장 크기로 유지하십시오. [가상 메모리 공간 권장사항](https://answers.microsoft.com/ko-kr/windows/forum/all/%EA%B0%80%EC%83%81/2586a8e5-0728-42b3-a259-2f76f918e6b9)


---
@this-is-spear 

> JVM을 통해 클래스 파일을 실행하게 되면 Swap 영역을 설정하지 않으면 OOM이 발생합니다. 
> 하지만 Swap 영역을 사용하게 되면 지연이 발생하기 때문에, 가급적 해당 영역을 사용하지 않도록 설계하는 것이 중요한데, 아래 내용들이 궁금해졌습니다.

![image](https://user-images.githubusercontent.com/53300830/185563122-3c665d67-c15d-4f80-9ecc-b661b689d0bc.png)

제가 아는 JVM은 위처럼 생겨서 `Swap` 영역을 설정한다는게 무슨 의미인지 제가 제대로 이해를 못했습니다. 
혹시 관련 레퍼런스 있으면 링크 주시면 감사하겠습니다!

---

**Comment by youngreal** [comment]
1. 가상 메모리란 무엇인가요?
=> 운영체제가 각프로세스에게 코드,데이터를 저장할수있는 가상의 연속된 주소공간을 가지게하는것
2. 가상 메모리를 사용했을 때 장점이 있을까요?
- 한 프로세스가 입출력을 실행하면 CPU가 다른 프로세스로 전환하여 사용할수있는등 CPU의 이용률이 올라 효율성을 개선할수있다.
- 사용자 프로그램이 물리메모리보다 커져도 된다는점

3. 이와 반대로 가상 메모리를 사용했을 때 단점이 있을까요
=> 근본적으로 물리적인 공간이 부족해져 내부단편화 문제가 생길수있으며  운영체제 입장에선 가상메모리를 사용해 효율성이 오르는대신 context switch, 운영체제가 주소공간이 저장될 메모리공간을 찾거나, 프로세스가 종료될때 메모리를 회수하여 다른 프로세스나 운영체제가 사용할수있게끔하는 연산이 추가될것같습니다
