### ISSUE TITLE
커널이란 무엇이고, 어떤 처리를 할까요?

### ISSUE THREAD

**Issue by this-is-spear** [Stacked-Book/os-hardware#2]
page, 책내용: 
1 장에서 커널과 관련된 내용이 나왔습니다.
질문:
운영체제에서 커널은 매우 중요한 처리를 담당하고 있습니다. 
그래서 커널은 무엇인지 그리고 어떤 처리를 진행하는지 알아보면 좋을 것 같습니다. ☺️
추가적으로 리눅스의 커널 모드에서는 [리눅스 커널](https://ko.wikipedia.org/wiki/%EB%A6%AC%EB%88%85%EC%8A%A4_%EC%BB%A4%EB%84%90?tableofcontents=0) 기반으로 동작하게 되는데 각 운영체제마다 제공하는 커널마다 고유한 특성이 있나 봅니다! 이와 관련되어서 정리하는 시간을 가져도 좋을 것 같습니다. 👍

**Comment by this-is-spear** [comment]
1. 커널 기반의 운영체제에서 하드웨어를 제어, 프로세스 제어, 메모리 제어 등 커널 모드에서 동작하는 OS 핵심 부분이 되는 처리를 모아 담당하는 프로그램을 커널이라 부릅니다.
2. 커널은 단일형 커널, 마이크로커널, 혼합형 커널 등 종류가 많습니다.
    1. 단일형 커널
        
        단일형 커널(monolithic kernel)은 입출력, 네트워크, 디바이스 지원 등등의 운영체제에서 일어나는 모든 일들을 한 개의 커널이 다 처리하는 방식입니다. 속도가 빠르고 디자인도 편리하지만, 잠재적 안정성 문제에 커널의 크기도 무지막지하게 커집니다. 
        **리눅스 커널은 단일형 커널에 속합니다.**
        
    2. 마이크로 커널
        
        시스템 콜 같은 서비스, 그리고 디바이스 관리를 제외하여 안정성을 높이고 커널 크기도 줄인 디자인 방식입니다. 
        
    3. 혼합형 커널
        
        단일형 커널에 마이크로커널 디자인을 집어넣어 만든 디자인 방식입니다.
        
        **Window 11 또한 혼합형 커널에 속하고 macOS와 IOS도 XNU 커널을 기반으로 하는데 XNU 커널도 혼합형 커널에 속합니다.**

**Comment by LudyPark** [comment]
#### 커널이란?

- 메모리에 상주하며 CPU에 명령을 내리는 소프트웨어입니다.

#### 커널 로드 과정

- 컴퓨터를 켜면 부트스트랩 프로그램이라는 초기화 프로그램이 실행됩니다. 
이 프로그램은 컴퓨터의 ROM이나 EEPROM에 저장되어 있으며 Firmware라고 불립니다.
- 부트스트랩 프로그램은 시스템을 초기화하고 부트로더를 실행시키는데 부트로더는 최종적으로 운영체제를 실행합니다.
  - 운영체제는 컴퓨터의 하드웨어를 관리하고, 하드웨어와 소프트웨어, 사용자를 매개하는 프로그램이며 커널과 커널 모듈들로 구성이 되어있습니다.
- 운영체제를 실행하므로써 커널이 로드, 실행됩니다.

#### 커널의 기능

- 메모리 관리 : 메모리가 어디에서 무엇을 저장하는 데 얼마나 사용되는지를 추적합니다.
- 프로세스 관리 : 어느 프로세스가 중앙 처리 장치(CPU)를 언제 얼마나 오랫동안 사용할지를 결정합니다
- 장치 드라이버 : 하드웨어와 프로세스 사이에서 중재자/인터프리터의 역할을 수행합니다.
- 시스템 호출 및 보안 : 프로세스의 서비스 요청을 수신합니다.

**Comment by Jaeeun1083** [comment]
#### 모드 비트 추가 설명

모드 비트가 커널모드 (1)이라면 CPU의 모든 메모리 영역에 접근 가능하지만 유저 모드(0)이라면 모든 메모리에 접근은 불가능하고 자신의 Address Space만 접근 가능하다. 

또한 커널모드일 경우 모든 instruction이나 op-code를 수행할 수 있지만 유저모드일 경우 I/O instruction이나 special register accesses(스택 포인터나 프로그램 카운터와 같은 특별한 레지스터의 값을 읽는 행위)와 관련된 instruction은 금지된다.

![image](https://user-images.githubusercontent.com/78838791/176114508-efd6c3d6-ce15-4f7b-a6be-9a44fd351a82.png)

- CPU와 메모리 사이에 MMU 하드웨어는 CPU에서 메모리로 가는 address 정보를 조사한다.
- 조사에 통과하면 Instruction Fetch 즉 instruction을 가져온다. instruction의 구조는 op-code와 operands로 구성된다. op-code를 통해 어떤 연산인지 확인한다.
- op-code(명령어)를 확인 후 만약  privileged op-code(I/O와 같은 중요한 역할을 하는 실행)을 시도하려 한다라고 판단되면 CPU를 운영체제로부터 박탈당한다.

> 모드 비트가 유저모드일 때, CPU가 접근하는 메모리 주소가 실행 중인 프로그램의 범위 밖이거나 I/O instruction등의 금지된 실행을 하려고 한다면 CPU를 운영체제로부터 박탈당한다. 
> 반대로 커널모드였을 경우는 위에서 언급한 검증 절차를 전혀 밟지 않아도 된다.

**Comment by youngreal** [comment]
## 커널
- 운영체제의 핵심부분으로  컴퓨터 하드웨어와 프로세스의 보안을 책임집니다
- 한정된 시스템 자원을 효율적으로 관리합니다
- 일관성 있는 인터페이스를 하드웨어에 제공하기위해 하드웨어 추상화가 구현되어있습니다

## 모놀리식 구조(단일 구조)

![image](https://user-images.githubusercontent.com/59333182/176356045-691c770e-d399-46a6-a43b-f045c6b05062.png)

커널의 모든기능을 단일 주소공간에 결합해논 구조입니다
**단순하지만 구현,확장하기가 어렵다는 단점이 있습니다** 

**근데도 여러 운영체제가  단일구조 기반인 이유는 무엇일까요?**

모놀리식 커널은 성능면에서 뚜렷한 이점이 있으며  
시스템 콜 인터페이스에는 오버헤드가 거의없고 커널안에서의 통신속도가 빠릅니다 
구현,확장하기가 어렵지만 속도와 효율성하나로 UNIX,Linux,Windows 운영체제에서 발견될수있는 구조입니다 


![image](https://user-images.githubusercontent.com/59333182/176356326-d04060b9-168f-4feb-a04e-e5fe1b44b47a.png)

리눅스는 단일주소공간에서 커널모드로 전부실행된다는 점에서 모놀리식 이지만
런타임 중에 커널을 수정할수있는 **모듈식 설계**를 갖추고 있습니다

## 모듈식 설계

커널은 핵심적인 요소를 가지고있고 부팅, 실행중에 부가적인 서비스들을 모듈을 통하여 링크 할수있습니다.
설계의 주안점이 커널은 핵심서비스를 제공하고 다른서비스들은 커널이 실행되는동안 동적으로 구현하는것입니다
동적으로 구현된다는것은 결국 수정이 일어났을때 생기는 비용들을 줄일수 있다는 점을 시사합니다 

리눅스,맥OS, 윈도우 등에서도 이러한 유형의 설계를 구현하는 추세입니다 

## 하이브리드 시스템 

사실 엄격하게 정의된 하나의 구조를 채택한 운영체제는 거의 존재하지않고 
다양한 구조를 결합하여 성능, 보안, 편리성 문제를 해결하려는 혼용구조로 구성된다고 합니다 

리눅스는 모놀리식구조 + 모듈  을 사용하는 구조이며
윈도우도 모놀리식구조 + 마이크로커널의 형태를 유지하고있습니다 
이외에도 맥os, iOS, 안드로이드 등

현대 운영체제는 대부분 하이브리드 시스템이구나 라고 생각하면 좋을것 같습니다
