### ISSUE TITLE
ppidloop.c 프로세스 비율관련

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/os-hardware#4]
page, 책내용: p.37 

요청하셨어서 올립니다 

질문: ppidloop 프로그램 프로세스 비율 관련 동영상
지난번엔 user72/system 28 
이번엔  user 53/ system 47로 나오네요???

https://user-images.githubusercontent.com/59333182/175213245-8671eb52-a65f-4074-8e6a-3be0c29e34e0.mp4

**Comment by this-is-spear** [comment]
혹시 소스코드 업로드 해주실 수 있나요? ☺️

**Comment by youngreal** [comment]
어떤 소스코드 말씀이신가요?? 책의 예제와 동일합니다 ~
