### ISSUE TITLE
PCB와 컨텍스트 스위치

### ISSUE THREAD

**Issue by LudyPark** [Stacked-Book/os-hardware#5]
page, 책내용: 4장 프로세스 스케줄러

질문:

1. CPU의 PC, 레지스터
2. PCB
3. 컨텍스트 스위칭
에 대해 개념을 한번 정리하고 넘어가면 좋을 것 같아요!

**Comment by youngreal** [comment]
운영체제가 CPU코어의 현재 작업 흐름을 뺏을때마다 인터럽트가 발생합니다.

인터럽트되면 하던일을 중단하고 즉시 특정위치로 실행을 옮기게 되는데 

그 실행을 마치고나면 원래의 연산을 처리하기위해 돌아와야합니다 

![image](https://user-images.githubusercontent.com/59333182/176212750-434a58da-8386-4775-9a2b-05e25a6fa1d0.png)

다시 돌아오기위해선 실행중인 프로세스의 context를 저장하게 되는데 
이때 **PCB(Process Control Block)** 에 저장하게 됩니다 

PC : 프로그램카운터, 이 프로세스가 다음에 실행할 명령어의 주소를 가리킵니다

레지스터 : 인터럽트 발생시 인터럽트 처리가 끝난후 다시 프로세스가 정상 처리될수있도록 상태정보를 저장합니다

PCB는 PC,레지스터,등등의 정보를 저장해두는 프로세스 제어 블록입니다 


![image](https://user-images.githubusercontent.com/59333182/176211892-c8837c53-6c2a-4939-9a25-018b1f330b34.png)

인터럽트가 발생하게되면 과거 프로세스의 context를 PCB에 저장하고
 실행이 예정된 새로운 프로세스에 저장된 context를 복구합니다 

이때, 새로운 프로세스의 보관된상태를 복구하는작업을 **context switch**라고 합니다 

이 context switch 가 진행될동안 시스템이 아무론 유용한일을 못하기때문에, 순수한 오버헤드라고 볼수있으며
교환속도는 메모리의속도, 복사되어야하는 레지스터의수, 특수명령어 등에 좌우되기떄문에 기계마다 다릅니다

**Comment by LudyPark** [comment]
#### CPU 레지스터

- 중앙처리장치(CPU) 내에 위치한 기억장치
- 종류
  - PC (Program Counter) : 다음 인출(Fetch) 될 명령어의 주소를 가지고 있는 레지스터
  - AC (Accumulator) : 연산 결과 데이터를 일시적으로 저장하는 레지스터
  - IR (Instruction Register) : 가장 최근에 인출된 명령어(현재 실행 중인 명령어)가 저장되어 있는 레지스터
  - SR (Status Register) : 현재 CPU 의 상태를 가지고 있는 레지스터
  - MAR (Memory Address Register) : PC 에 저장된 명령어 주소가 사용되기 전에 일시적으로 저장되는 주소 레지스터
  - MBR (Memory Buffer Register) : 기억장치에 저장될 데이터 혹은 읽혀진 데이터가 일시적으로 저장되는 버퍼 레지스터

#### PCB

![image](https://user-images.githubusercontent.com/78838791/176121553-106b70b8-9da7-4422-be45-daba67029f70.png)
- 운영체제가 프로세스를 제어하기 위해 프로세스 상태 정보를 저장하는 구조체이다.
- 프로세스 상태 관리와 컨텍스트 스위칭을 위해 필요하다.
- PCB에는 다음과 같은 정보들이 들어있다.
   - PID : 프로세스 번호
   - Priority : 스케줄링 및 프로세스 우선순위
   - Process State : 프로세스의 준비, 대기, 실행 등의 상태
   - Program Counter : 해당 프로세스가 이어서 실행해야 할 명령의 주소 값
   - CPU registers : 프로세스가 인터럽트 이후 올바르게 작업을 이어가기 위해 참조하는 CPU 레지스터 값.
   - CPU-scheduling information: 프로세스의 중요도, 스케줄링 큐 포인터 등 스케줄링 파라미터 정보.
   - Memory-management information: base, limit 레지스터 값, 페이지 테이블 등 메모리 시스템 정보.
   - Accounting information: 사용된 CPU 총량, 프로세스 개수, 시간 제한 등.
   - I/O status information: 프로세스에 할당된 입출력 장치 목록, 열린 파일 목록 등.

- 운영체제는 PCB에 빠르게 접근하기 위해 프로세스 테이블을 사용하여 각 프로세스의 PCB를 관리한다.

#### 컨텍스트 스위칭

- 현재 진행하고 있는 Task(Process, Thread)의 상태를 저장하고 다음 진행할 Task의 상태 값을 읽어 적용하는 과정이다.
   - Task의 대부분 정보는 Register에 저장되고 PCB(Process Control Block)로 관리된다.
   - 현재 실행하고 있는 Task의 PCB 정보를 저장한다. (Process Stack, Ready Queue)
   - 다음 실행할 Task의 PCB 정보를 읽어 Register에 적재하고 CPU가 이전에 진행했던 과정을 연속적으로 수행할 수 있다.

**Comment by this-is-spear** [comment]
> PCB는 PC,레지스터,등등의 정보를 저장해두는 프로세스 제어 블록입니다

@youngreal 글을 읽고 질문이 생겨서 코멘트 남깁니다. ☺️

1. PCB는 그럼 운영체제 안에 존재하는 영역이 되는건가요?  이 영역은 메모리로 생각하면 될까요? 🥺
2. 전체적인 동작은 아래처럼 진행하는게 맞을까요? 
    1. 다른 프로세스를 동작하기 위해 현재 프로세스 Context를 PCB에 저장한다.
    2. 동작하는 프로세스를 처리한다.
    3. 다음 처리해야할 프로세스를 PCB에서 꺼낸다.

 이렇게 PCB에서 꺼내서 복구하는 상황을 Context Switch라고 생각하면 되겠군요!  좋은 정보 감사합니다. ☺️

**Comment by youngreal** [comment]
> 

@this-is-spear 

#### 1. PCB는 그럼 운영체제 안에 존재하는 영역이 되는건가요? 이 영역은 메모리로 생각하면 될까요? 🥺
=> PCB는 프로세스의 중요한정보(프로세스의 메타데이터)를 포함하고있기때문에 **일반사용자가 접근하지 못하도록 보호된 메모리영역** 안에 남습니다. 

이 메모리영역은 편리하고, 안전하게 보호되는 위치이기때문에 일부 운영체제에서는 PCB가 **커널스택의 처음에 위치**한다고 하네요 

**커널스택에 대한 부가설명**

일반적인 프로세스는 유저모드Stack, 커널모드Stack을 각각 하나씩 가지고있습니다
이로인해 시스템호출이나 인터럽트 발생시마다 레지스터가 유저모드Stack의 top부분을 가리키다가 
커널모드로 전환이 된다면 커널모드stack의 top을 가리키게되는 현상이 가능하게 됩니다

각각의 stack 부분을 넘나들면서 전환되기전에 필요한 정보중 일부를 저장할 필요가 있게되고 
이에따라 각각의 모드에 stack이 존재하게 된것이 아닐까 라는 생각이 듭니다  

더궁금하시다면 찾고 공유해주시면 좋을것 같네요 ㅎㅎ


**2. 전체적인 동작은 아래처럼 진행하는게 맞을까요?**
=> 맞습니다ㅎㅎ 

두번째 과정 **동작하는 프로세스를 처리한다.** 부분을 조금더 디테일하게 풀자면

프로세스A 실행중 인터럽트 혹은 시스템콜 발생 ->  
**(프로세스 A,B 둘다 유휴상태 시작) PCB에 프로세스A의 상태를 저장하는 작업수행 -> 
 새로 실행이 예정된 프로세스B의 상태를 복원하는 작업 ( 프로레스 A,B  둘다 유휴상태로 들어가기때문에 길어지면 치명적입니다)**  
->새로 실행이 예정된 프로세스B 실행 입니다.

굵게표시된 부분은 아예 A,B 프로세스 둘다 중단되는 부분으로, context switch 가 이부분입니다 
 
정리하자면 말씀하신것처럼 
**진행중인 프로세스 A를  PCB에 상태를 저장한후, 실행될 프로세스B의 상태를 복원하는 시간이 있습니다** (이시간들은 A,B프로세스 모두 유휴상태입니다) 이부분이 context switch 인것이고 순수한 오버헤드인 부분인것이죠  
그림이랑 같이보시면 이해가 더 잘될것 같아요 


유휴상태: 어떠한 프로그램에 의해서도 사용되지 않는상태

**Comment by lee-ji-hoon** [comment]
## CPU의 PC, 레지스터

### CPU 레지스터
> 중앙처리(CPU) 내에 위치한 기억장치로 많은 수의 레지스터를 CPU내에 포함시키는 것은 어렵기 때문에 특수 목적용 레지스터들과 몇몇 일반 목적용 레지스터만 존재한다.

### CPU Program Counter(PC)
> 중앙 처리 장치 내부에 있는 레지스터 중 하나로서, 다음에 실행될 명령어의 주소를 가지고 있어 실행할 기계어 코드의 위치를 지정합니다.  
때문에 명령어 포인터라고도 합니다.

## PCB

![image](https://user-images.githubusercontent.com/53300830/181730546-a9328aa2-45e6-4586-ad67-e5a36ba843f6.png)

- 프로세스 상태 : 생성, 준비, 수행, 대기, 중지
- 프로스램 카운터
- 레지스터
- 프로세스 번호

### 이러한 PCB가 필요한 이유
> CPU 에서는 프로세스의 상태에 따라 교체 작업이 이루어집니다.    
-> 인터럽트가 발생해서 할당받은 프로세스가 Block 상태가 되고, 다른 프로세스를 running 으로 바꿀때!

![image](https://user-images.githubusercontent.com/53300830/183034219-641cdfd4-2ab6-4aa8-9b18-097e2f914aec.png)
> 생성 -> 준비 -> 실행 -> 대기 ->  준비 -> 실행 -> 종료

** 앞으로 다시 수행할 Block 상태의 프로세스의 상태값을 PCB에 저장해두는 것입니다! **

### 관리 방식
> PCB는 LinkedList로 관리가 됩니다.
- PCB List  Head에 PCB들이 생성될 때마다 붙게 됩니다.  
- 주솟값으로 연결이 이루어져 있는 연결 리스트 형태로 삽입 삭제가 용이합니다.   

** 즉 프로세스가 생성되면 해당 PCB가 생성되고, 프로세스 완료시 제거됩니다.  **  

> 이렇게 수행중인 프로세스를 변경할 때, CPU 레지스터 정보가 변경되는 것을 Context Switching 이라고 합니다.

## 컨텍스트 스위칭
> 어떤 하나의 프로세스를 실행하고 있는 상태에서 인터럽트 요청에 의해 다음 우선 순위의 프로세스가 실행되어야 할 때 기존의 프로세스의 상태 또는 레지스터 값(Context)을 저장하고 CPU가 다음 프로세스를 수행하도록 새로운 프로세스의 상태 또는 레지스터 값(Context)를 교체하는 작업을 컨텍스트 스위칭이라고 합니다.
- 이러한 컨텍스트 스위칭때 해당 CPU는 아무런 작업을 하지 못하여 오버헤드가 발생하여 효율이 떨어지게 됩니다.

### 컨텍스트 스위칭은 아래와 같은 상황에서 일어납니다.
1. I/O interrupt
2. CPU 사용시간 만료
3. 자식 프로세스 Fork
4. 인터럽트 처리를 기다릴 때

### 컨텍스트 스위칭시에는 해당 쓰레드만의 스택 영역이 생성된다.
- 나머지 영역 Code, Data, Heap은 부모 프로세스 영역에서 공유하고 있다.
- 쓰레드 마다 스택을 독립적으로 할당해준다.
- 프로세스는 레지스터 수, 프로세스에서 관리돼야 할 데이터 종류가 많을수록 부담이 된다.
- 컨텍스트 스위칭에 소요되는 시간을 줄이려면 저장하고 복원되는 컨텍스트 정보를 줄여야 한다.  
> 스레드는 공유 영역이 많기 때문에 컨텍스트 스위칭이 빠르다.

**Comment by this-is-spear** [comment]
### 레지스터

레지스터는 CPU 안에 있는 가장 빠른 임시기억장치를 의미하고, CPU는 자체적으로 데이터를 저장할 방법이 없기 때문에 레지스터를 거쳐 데이터를 전달하게 됩니다.

### PCB

PCB는 운영체제에서 프로세스에 대한 메타데이터를 저장한 데이터를 말하며 프로세스 제어 블록이라고도 합니다. 프로세스가 생성이 되면 운영체제는 해당 프로세스의 메타데이터가 들어간 PCB를 생성하게 됩니다.

프로그램이 실행되면 프로세스가 생성되고 프로세스 주소 값들에 스택, 힙 등의 구조를 기반으로 메모리가 할당됩니다. 그리고 프로세스의 메타데이터들이 PCB에 저장되어 관리됩니다. PCB는 프로세스의 중요한 정보를 포함하고 있기 때문에 일반 사용자가 접근하지 못하도록 커널 스택의 가장 앞 부분에서 관리됩니다.

### 컨텍스트 스위칭

컨텍스트 스위칭은 앞서 설명한 PCB를 교환하는 과정을 말합니다. 한 프로세스에 할당된 시간이 끝나거나 인터럽트에 의해 발생하게 됩니다. 또한 캐시미스로도 컨텍스트 스위칭 비용이 발생하게 됩니다.

### 캐시미스

컨텍스트 스위칭이 일어날 때 프로세스가 가지고 있는 메모리 주소가 그대로이면 잘못된 주소 변환이 생기기 때문에 캐시 클리어과정을 겪고, 캐시 클리어 과정 때문에 캐시미스가 발생하게 됩니다.
