### ISSUE TITLE
Process vs Thread 

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/os-hardware#6]
page,책내용: 4장 프로세스 스케줄러

질문: 

1. 프로세스와 스레드의 차이가 무엇인가요?
2. 멀티스레드와 멀티프로세스 가 사용되는 예시를 들어주시고 각각의 장단점을 말씀해주세요
3. 프로세스끼리의 데이터공유, 스레드끼리의 데이터공유의 공통점과 차이점이 무엇인가요 
4. 멀티프로세스의 context switch, 멀티스레드의 context switch 는 어떤 차이점이있을까요?

프로세스 이야기와 context switch 이야기가 나오기때문에 관련해서 공부해보면 좋은내용인것 같아요

**Comment by youngreal** [comment]
### 1.프로세스와 스레드의 차이가 무엇인가요?

프로세스: 실행중인 프로그램의 인스턴스를 뜻하며 운영체제로부터 시스템 자원을 할당받는 작업의 단위입니다
(Code,Data,Stack,Heap의 구조로 되어있음)
 다른 프로세스의 변수나 자료구조에 접근이 불가능합니다

스레드: CPU 이용의 기본단위로 프로세스가 할당받은 자원을 이용하는 실행의 단위입니다.
같은 프로세스에 속한 다른스레드와 코드,데이터섹션, heap과 같은 운영체제 자원들을 공유합니다 
한 스레드가 프로세스 자원을 변경하면  다른스레드에서 그 변경결과를 볼수있습니다 



### 2. 멀티스레드와 멀티프로세스 가 사용되는 예시를 들어주시고 각각의 장단점을 말씀해주세요

#### 멀티 프로세스 예시 - 크롬브라우저 
웹 브라우저가 오직 한탭만 보여준다면 크게 문제가 될수 없겠지만 
현대 웹 브라우저들은 여러 탭형식의 브라우징을 지원하므로 탭중 하나라도 고장난다면 다른 탭을 포함한 전체 프로세스도 같이 고장난다는 문제점이 있을수 있다. 

크롬은 디스크와 네트워크 I/O를 관리하는 책임을 지는 브라우저 프로세스,  HTML,JS,이미지등을 처리하기위한 렌더러 프로세스, 
Flash또는 QuickTime과같이 사용중인 플러그인 종류마다 생성되는 플러그인 프로세스로 구분하여 
만약 한 웹사이트가 고장나면 해당 렌더러 프로세스만 영향을 받고 나머지 프로세스는 손해를 입지 않는구조로 위의 문제를 해결하였다

https://blog.chromium.org/2008/09/multi-process-architecture.html  크롬의 탭하나하나는 프로세스다 

#### 멀티프로세스의 장단점
장점 : 여러 자식 프로세스중 하나가 죽어도 다른 프로세스에 영향을 미치지않는다
단점 : 멀티 스레드보다 많은 메모리공간, cpu시간을 차지하며,  멀티스레드보다 Context switch 의 오버헤드가 크다 
=> 단순히 CPU레지스터 교체뿐아니라, RAM,CPU사이의 캐시메모리에 대한 데이터까지 초기화되기때문이다

#### 멀티스레드 예시 - 텍스트 편집기

입력할때 텍스트를 입력받으면서 맞춤법검사, 키보드응답, 서식지정등이 동시에 발생합니다
내부적으로 이러한 작업을 독립적으로 수행하는 다른 스레드가 있습니다 

#### 멀티스레드의 장단점
장점 
- 둘 이상의 작업을 병렬로 처리할수있기때문에 속도적인 이점이 있다

- 프로세스의 context switch보다 스레드의 context switch가 더 빠르다

- 새작업을 하기위해 프로세스를 새로 생성하기위해 메모리와 자원을 할당하는것보단
자신이 속한 프로세스의 자원을 공유하는 스레드를 생성하는것이 시간과 메모리를 덜 소비한다

단점 
- 하나의 스레드만 종류되어도 전체 스레드가 종료될수있다. 
 
- 동기화 문제가 발생할수있다 . 

- 임계영역, 스레드 스케줄링 등의 문제를 신경써주어야한다 


## 3.프로세스끼리의 데이터공유, 스레드끼리의 데이터공유의 공통점과 차이점이 무엇인가요

**프로세스 데이터공유**

![image](https://user-images.githubusercontent.com/59333182/176407741-4d0063a5-d5b4-4754-9d99-8e9ced2300a6.png)


기본적으로 다른 프로세스의 변수나 자료구조에 접근이 불가능하지만
다음의 이유들로 서로 협력할수있습니다 

- 계산 가속화 : 특정 task를 빨리 실행하고자 할때, 서브task로 나누어 각각 다른 서브task들과 병렬로 실행되게 할수있다. 
(이는 멀티코어 이상에서만 가능합니다)

- 모듈성 : 커널 구조를 공부하면서 잠깐 이야기가 나왔었는데 시스템 기능을 별도의 프로세스,스레드 별로 나누어 모듈형태로 시스템을 구성할수 있습니다

- 정보공유: 여러 응용프로그램이 동일한정보를 필요로하는경우 그러한 정보를 병행적으로 접근하도록 할수있다. 

파이프,파일,소켓 등을 이용해 다른 프로세스의 자원에 접근해야합니다 스레드간 데이터공유보다 과정이 까다로운것 같습니다


**스레드 데이터공유**

![image](https://user-images.githubusercontent.com/59333182/176407003-ffff6bf1-ad4b-4aca-aded-c06901958464.png)

프로세스 내에서 스택은 할당받고 힙,데이터, 텍스트(실행코드) 영역은 공유합니다 

**공통점차이점?**

공통점 : 필요시 자원을 공유할수있다는점?

차이점 : 프로세스는 기본적으로 독립된 메모리영역을 할당받으며, 접근하기위해선 추가적인 까다로운 절차 ( 파이프, 파일, 소켓등) 와 비용이 필요하지만 스레드는 그에비해 자원공유의 부담이 적은편이다 



## 4. 멀티프로세스의 context switch, 멀티스레드의 context switch 는 어떤 차이점이있을까요?

프로세스는 각각 독립된 메모리영역을 할당받아 context switch 발생시 많은 오버헤드가 발생하는 반면

스레드에서는 스택영역을 제외한 모든 메모리를 공유하기때문에 

프로세스의 context switch 보다 비용, 시간이 덜 걸립니다

**Comment by LudyPark** [comment]
### 프로세스와 스레드의 차이

#### 프로세스란?

- 메모리에 올라와 실행되고 있는 프로그램의 인스턴스
- 운영체제로부터 시스템 자원을 할당받는 작업의 단위
   - 할당 받는 시스템 자원은 CPU 시간, 운영에 필요한 주소 공간, Code,Data,Heap 구조로 되어있는 독립된 메모리 영역
- C프로그램의 메모리 레이아웃 예제
  ![image](https://user-images.githubusercontent.com/78838791/177436714-6dd07d29-9929-4fbe-a6b9-3274242816c5.png)

#### 프로세스의 특징

- 기본적으로 프로세스당 최소 1개의 스레드(메인 스레드)를 가지고 있다.
- 각 프로세스는 별도의 주소 공간에서 실행되며, 한 프로세스는 다른 프로세스의 변수나 자료구조에 접근할 수 없다.
- 한 프로세스가 다른 프로세스의 자원에 접근하려면 프로세스 간의 통신(IPC, inter-process communication)을 사용해야 한다.  

#### 스레드란?

- 프로세스의 특정한 수행 경로
- 프로세스가 할당받은 자원을 이용하는 실행의 단위

#### 스레드의 특징

- 스레드는 프로세스 내에서 각각 Stack만 따로 할당받고 Code, Data, Heap 영역은 공유한다.
- 스레드는 한 프로세스 내에서 동작되는 여러 실행의 흐름으로, 프로세스 내의 주소 공간이나 자원들(힙 공간 등)을 같은 프로세스 내에 스레드끼리 공유하면서 실행된다.
- 각각의 스레드는 별도의 레지스터와 스택을 갖고 있지만, 힙 메모리는 서로 읽고 쓸 수 있다.
- 한 스레드가 프로세스 자원을 변경하면, 다른 이웃 스레드(sibling thread)도 그 변경 결과를 즉시 볼 수 있다

### 멀티스레드와 멀티프로세스가 사용되는 예시, 각각의 장단점

#### 멀티 프로세스

![image](https://user-images.githubusercontent.com/78838791/176372249-5adc0c4f-780d-49ab-97eb-6e0282fb111c.png)

- 하나의 응용프로그램을 여러 개의 프로세스로 구성하여 각 프로세스가 하나의 작업(태스크)을 처리하도록 하는 것이다.
- 장점
   - 여러 개의 자식 프로세스 중 하나에 문제가 발생하면 그 자식 프로세스만 죽는 것 이상으로 다른 영향이 확산되지 않는다.
- 단점
   - 컨텍스트 스위칭에서 오버헤드
      - 프로세스는 각각의 독립된 메모리 영역을 할당받았기 때문에 프로세스 사이에서 공유하는 메모리가 없어 프로세스 간의 Context Switching 시 단순히 CPU 레지스터 교체 뿐만 아니라 RAM과 CPU 사이의 캐쉬 메모리에 대한 데이터까지 초기화되므로 오버헤드가 크다.
   - 프로세스 사이의 통신이 복잡하고 어렵다.

#### 멀티 스레드

![image](https://user-images.githubusercontent.com/78838791/176372132-551e7ab1-4bfb-4824-b6ca-0e5cf25eefdf.png)

- 하나의 응용프로그램을 여러 개의 스레드로 구성하고 각 스레드로 하여금 하나의 작업을 처리하도록 하는 것이다.
- 장점
   - 시스템 자원 소모 감소 (자원의 효율성)
      - 프로세스를 생성하며 자원을 할당하는 
   - 시스템 처리량 증가
   - 간단한 통신 방법으로 인해 프로그램 응답 시간 단축
- 단점
   - 다른 프로세스에서 스레드를 제어할 수 없다.
   - 멀티 스레드의 경우 자원 공유의 문제가 발생한다.
   - 하나의 스레드에 문제가 발생하면 전체 프로세스가 영향을 받는다.

**Comment by lee-ji-hoon** [comment]
## ❓ 프로세스와 스레드의 차이가 무엇인가요?
> 프로세스와 스레드를 우선 각각 알아보는 것이 좋을 것 같습니다.
### 1. 프로세스
- 저희가 보통 코딩을 할 때는 IDE를 키고, 노래를 들으면서, 다양한 SNS를 켜놓습니다.  
- 이 때 각각의 프로그램이 실행되기 위해서는 각각의 프로세스가 할당됩니다. 즉 프로그램의 인스턴스라고 볼 수 있습니다.

**이렇게 프로그램이 프로세스가 되면서 일어나는 일은 2가지가 있습니다.** 
- 프로세스가 필요로 하는 재료들이 메모리에 올라온다.

![image](https://user-images.githubusercontent.com/53300830/179340192-e5bf43f4-e315-4afb-9c11-d5ba25593352.png)

- 해당 프로세스에 대한 정보들이 담고 있는 PCB 블럭이 프로세스 생성과 함께 만들어집니다.

![image](https://user-images.githubusercontent.com/53300830/179340251-e0627067-4c42-4209-9090-1c4c2b791dfa.png)

> 이렇게 우리는 하나의 일을 할 때 하나의 프로세스만 사용하기 보다는 수많은 프로세스를 사용하고 있습니다.

### 2. 스레드 
> 프로세스가 할당받은 자원을 이용하는 실행의 단위입니다.   
> 간단한게 생각하자면 쓰레드는 프로세스의 경량화된 버전이라고도 생각할 수 있습니다.  

![image](https://user-images.githubusercontent.com/53300830/179340279-6dcfb343-b5e6-49e1-95e9-bc4b5dd92898.png)

- 쓰레드는 `Code` `Data` `Heap` 은 부모 프로세스의 영역을 공통으로 사용합니다.
- 즉 `Stack` 영역만 각자 사용을 하는 것입니다.
- 공유되는 자원이 있기 때문에 컨텍스트 스위칭이 일어날 때 캐시 적중률이 올라가게 됩니다!
- 이를 간단하게 말하자면 모조리 다 빼고 다 넣고 할 필요가 없다는 의미입니다.

## ❓ 멀티스레드와 멀티프로세스 가 사용되는 예시를 들어주시고 각각의 장단점을 말씀해주세요
### 1. 멀티 쓰레드 예시 - 인텔리제이
저희는 보통 코딩을 할 때 특정 IDE를 사용합니다. 저는 주로 사용중인 인텔리제이로 예시를 들겠습니다.
- 코딩을 하면서 중간중간 인텔리제이에서 자동적으로 더 좋은 코드가 있으면 추천을 해준다.
- 테스트도 돌리는 동시에 코드도 수정해야 할 수도 있다.
> 이렇게 한 어플리케이션에 대한 작업의 단위가 나눠질 때가 많은데, 이 때 각각의 쓰레드가 그 작업들을 해당하게 됩니다.

### 2. 멀티 프로세스 예시 - 크롬
> 크롬의 하나하나의 탭은 쓰레드가 더 나아보이는데 왜 프로세스인 것이지?  
> 라는 생각을 할 수도 있습니다. 이해를 위해서 예전에 사용하던 익스플로어와 크롬을 예시로 들겠습니다!

- 예전 익스플로어에서 여러개의 탭을 쓰다가 멈춘 경험이 있을 것입니다.
- 그럴 때 중간에 작동이 중단이 되고 모든 프로세스가 종료 됩니다.
- 즉 하나의 쓰레드(하나의 탭)이 문제가 생기면 전체 프로세스에 영향이 가게 됩니다.
- 반면 구글은 멀티 프로세스를 이용하기 때문에 멀티탭 간의 영향을 주지 않습니다! 

![image](https://user-images.githubusercontent.com/53300830/179340953-3e392f93-167f-4f14-8efd-1ec1c8f3c929.png)

## ❓ 프로세스끼리의 데이터공유, 스레드끼리의 데이터공유의 공통점과 차이점이 무엇인가요
> 우선은 프로세스와 스레드 각각의 데이터 공유 방법부터 알아보고 공통점과 차이점을 이야기 해보겠습니다.

### 1. 프로세스끼리의 데이터 공유
![image](https://user-images.githubusercontent.com/53300830/179341069-4713e343-93f4-43bf-9b2a-27615d23ee1b.png)

**A. 공유 메모리(shared memory)**
- 커널의 통신 서비스를 이용해 협력하는 프로세스들 사이에 공유되는 메모리 영역(shared memory)를 구축하는 방법
- 메모리를 직접 접근하기 때문에 속도가 빠르고 사용이 편리하다.
> 단 프로세스A가 공유 메모리에 데이터를 전달해도 프로세스 B가 그것을 알 수 없다. 즉 별도의 동기화 기술이 필요하다!..

**B. message passing**
- 운영체제 커널 메모리 영역에 메시지 전달을 위한 채널을 만들어서 협력하는 프로세스들 사이에 메시지 형태로 정보는 send/receive 하는 방식
- 커널에서 데이터의 주고 받음을 컨트롤할 수 있어 별도의 동기화 로직은 필요 없다.
> 하지만 커널을 통해서 데이터를 주고 받기 때문의 성능 문제를 야기할 수 있다.

### 2. 스레드끼리의 데이터 공유
> 동일 프로세스 내부의 Stack 제외한 공유 메모리 영역이 존재한다.
지역변수, 전역변수를 통해 데이터 공유가 가능하기도 하다.

### 3. 공통점과 차이점
공통점으로는 서로 다른 환경의 내용을 공유할 수 있다는 것이다.  

차이점은 너무나도 많다.
- 멀티 스레드는 프로세스의 공유 자원에 접근을 하기 때문에 멀티 프로세스의 공유보다 훨씬 간편하다.
- 단 멀티 스레드는 공유 자원이라는 개념 때문에 동기화에 조금 더 신경을 써야만 한다.

## ❓ 멀티프로세스의 context switch, 멀티스레드의 context switch 는 어떤 차이점?

### 컨텍스트 스위칭 차이 예시
> 희의실을 예시로 들겠습니다.  
> 회의실에는 공용으로 사용하는 `TV` `리모콘` `스피커` `화이트보드` 등이 있습니다.  

- 프로세스의 컨텍스트 스위칭은 공통으로 사용할 `TV` `리모콘` `스피커` `화이트보드` 까지 갖고 나가고 새로 갖고 들어옵니다.
- 쓰레드의 컨텍스트 스위칭은 공통으로 사용할 `TV` `리모콘` `스피커` `화이트보드` 은 두고 개인 물품(Stack)만 갖고 옵니다.

이처럼 프로세스는 많은 오버헤드가 생기는 반면 쓰레드는 공유 자원은 존재하므로 프로세스의 비해 오버헤드가 적습니다.

## 참고
[10분 테크톡 - 코다의 Process vs Thread](https://www.youtube.com/watch?v=1grtWKqTn50&t=403s&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9CTech)
[반효경[운영체제] Process 1, 2, 3](https://core.ewha.ac.kr/publicview/C0101020140321141759959993?vmode=f)

**Comment by this-is-spear** [comment]
### 1. 프로세스와 스레드의 차이가 무엇인가요?

**프로세스**

프로세스는 컴퓨터에서 실행되고 있는 프로그램을 말하며 CPU 스케줄링의 대상이 되는 작업이라는 용어와 같은 의미로 사용됩니다. 

**스레드**

스레드는 프로세스 내 작업의 흐름을 지칭합니다.

### 2. 멀티스레드와 멀티프로세스 가 사용되는 예시를 들어주시고 각각의 장단점을 말씀해주세요

**멀티스레드가 사용되는 예시**

멀티스레딩 예로는 웹 브라우저의 렌더러 프로세스를 예로 들 수 있습니다.

**장점**

웹 요청을 처리할 때 새 프로세스를 생성하는 대신 스레드를 사용하는 웹 서버의 경우 훨씬 적은 리소스를 소비하며 한 스레드가 중단(blocked)되어도 다른 스레드는 실행(running) 상태일 수 있기 때문에 중단되지 않은 빠른 처리가 가능하다. 또한 동시성에도 큰 장점이 있습니다.

**단점**

한 스레도에 문제가 생기면 다른 스레드에도 영향을 끼쳐 스레드로 이루어져 있는 프로세스에 영향을 줄 수 있는 단점이 있습니다.

 **멀티프로세스가 사용되는 예시**

웹 브라우저는 멀티 프로세스 구조를 갖고 있습니다.

**장점**

하나 이상의 일을 병렬로 처리할 수 있으며 특정 프로세스의 메모리, 프로세스 중 일부에 문제가 발생되더라도 다른 프로세스를 이용해서 처리할 수 있으므로 신뢰성이 높은 강점이 있습니다.

**단점**

멀티스레드에 비해 많은 리소스를 소비합니다.

### 3. 프로세스끼리의 데이터공유, 스레드끼리의 데이터공유의 공통점과 차이점이 무엇인가요

**공통점**

데이터를 주고받는 것이 아닌 메모리 자체를 공유하기 때문에 불필요한 데이터 복사의 오버헤드가 발생하지 않아 가장 빠르며 같은 메모리 영역을 여러 프로세스가 공유하기 때문에 동기화가 필요합니다.

**차이점**

프로세스는 코드, 데이터, 스택, 힙을 각각 생성하지만, 스레드는 코드, 데이터, 힙은 스레드끼리 서로 공유한다. 그래서 프로세스는 메모리가 완전히 공유되는 스레드보다 속도가 떨어집니다. 

### 4. 멀티프로세스의 context switch, 멀티스레드의 context switch 는 어떤 차이점이있을까요?

**context switch**

컨텍스트 스위칭은 PCB를 교화하는 과정에서도 일어나고 캐시미스로도 발생을 합니다.

**차이**

스레드는 스택 영역을 제외한 모든 메모리를 공유하기 때문에 스레드 컨텍스트 스위칭의 경우 비용이 더 적고 시간이 더 적게 걸립니다.
