### ISSUE TITLE
IPC와 파이프는 무엇인가요?

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/os-hardware#7]
1. IPC에 대해서 설명해주세요
2. 파이프는 무엇일까요?

**Comment by youngreal** [comment]
### 1. IPC에 대해서 설명해주세요
프로세스는 다른프로세스들과 데이터를공유하지않는 프로세스와, 협력하는 프로세스가 있는데 
협력적 프로세스들끼리 데이터를 교환할수있는 통신수단이 필요하며 그 기법을 IPC(프로세스간 통신) 이라고 합니다.
클라이언트가 데이터를 요청하고 서버는 응답하는것도 IPC의 예입니다

![image](https://user-images.githubusercontent.com/59333182/177458326-6af6bbbc-e240-45f0-8c84-3a5b56a0bcb8.png)

통신하는 프로세스들이 공유 메모리영역을 구축하여 공유영역에 프로세스들이 읽고쓰며 정보를 교환할수있는 
 **공유메모리 방식**과  동일한 주소공간을 공유하지않고도 프로세스들 사이에 교환되는 메시지를 통하여 통신이 이루어지는 **메시지 전달 시스템**이 있습니다  이외에도 소켓,파이프를 이용한 통신도 IPC의 사례입니다


### 2. 파이프는 무엇일까요?
두 프로세스가 통신할수있게 하는 전달자 입니다. 
파이프를 구현하기위해선 단방향, 양방향 통신인지
양방향 통신이라면 반이중방식(한번에 한방향 전송) 인지, 전이중방식(동시에 양방향 전송가능) 인지 고려해야합니다

**Comment by LudyPark** [comment]
#### IPC(InterProcess Communication)란?

- 프로세스가 실행되는 방식은 프로세스가 상호 독립적인 방식(independent processes)과 협력적인 방식(cooperationg processes)으로 나뉜다.
- 협력적인 방식일 경우 다른 프로세스와 서로 영향을 주고 받고 데이터를 공유해야한다.
- 이 때 프로세스간 데이터를 주고 받는 동작 또는 그에 대한 방법을 IPC라고 한다.

#### IPC의 종류

- shared memory
- message passing

#### shared memory

- 생산자와 소비자가 공유하는 어떤 메모리 영역을 의미한다.
- 버퍼를 이용하여 생산자는 버퍼를 채울 수 있고 소비자는 버퍼를 가져갈 수 있도록 한다.
- 버퍼는 unbounded buffer와 bounded buffer로 나뉜다.
   - unbounded buffer : 버퍼 크기에 한계가 없다.
   - bounded buffer : 고정 크기의 버퍼를 사용한다. 소비자는 버퍼가 비어있을 때 생상자는 버퍼가 가득 차있을 때 대기해야한다.
- 예제
   ```
   #### 버퍼 구조 ####
   #define BUFFER_SIZE 10
   typedef struct {
       ...
   } item;

   item buffer[BUFFER_SIZE];
   int in = 0;
   int out = 0;
   

   #### 생산자 코드 ####
   item next_produced;
   
   while (true) {
       /* next_produced에 아이템 생산 */
       
       while ((in + 1) % BUFFER_SIZE) == out) {
          	; /* 아무 것도 안 함 */
       }
    
       buffer[in] = next_produced;
       in = (in + 1) % BUFFER_SIZE;
   }

 
   #### 소비자 코드 ####
   item next_consumed;
   
   while (true) {
       while (in == out) {
       	   ; /* 아무 것도 안 함 */
       }
    
       next_consumed = buffer[out];
       out = (out + 1) % BUFFER_SIZE;
    
       /* next_consumed에 있는 아이템을 소비 */
   }
  ```

> shared memory 방식의 문제는 메모리 영역을 공유하게 될 때 메모리 영역에 명시적으로 액세스하거나 관리를 모두 프로그래머가 해야한다는 것이다. 공유가 많아질 수록 복잡해진다.


#### message passing

- 메시지를 주고 받는 프로세스에 O/S에서 수단을 제공하는 것이다.
- 즉 shared memory 관리를 O/S가 하는 것이다.
- message passing은 send(message), receive(message) 두가지 연산을 제공한다.
- 프로세스 간 통신을 위해서는 서로에게 반드시 메시지를 받아야한다 즉 communication link가 있어야한다. link는 다양한 방법으로 구현될 수 있다.
   - 직 / 간접 통신
   - 동기 / 비동기 통신
   - 자동 / 명시적 버퍼링

#### IPC System의 예시

- Shared Memory : POSIX Shared Memory
   - POSIX : Unix 계열에서 운영체제 표준화를 한 것이다.
- Message Passing : Pipes
   - Unix에서 가장 기본적인 구현 방법 중 하나이다.

#### POSIX Shared memory

- POSIX 공유 메모리는  메모리에 매핑된 파일 (memory-mapped file)을 사용한다.
- 예제
   ```
   int main()
   {
       /* 공유 메모리 개체의 크기 (바이트 단위) */
       const int SIZE = 4096;
       /* 공유 메모리 개체의 이름 */
       const char *name = "OS";
       /* 공유 메모리에 쓸 문자열 */
       const char* message_0 = "Hello";
       const char* message_1 = "World!";
    
       /* 공유 메모리 파일 설명자 */
       int fd;
       /* 공유 메모리 개체를 가리키는 포인터 */
       char *ptr;
    
       /* 공유 메모리 개체 생성 */
       fd = shm open(name,O CREAT | O RDWR,0666);
    
       /* 공유 메모리 개체 크기 설정 */
       ftruncate(fd, SIZE);
    
       ######## 생산자 코드 와 소비자 코드의 다른 부분 ########

       ######## 생산자 코드 ########
       /* 공유 메모리 개체를 메모리에 매핑 */
       ptr = (char*) mmap(0, SIZE, PROT READ | PROT WRITE, MAP SHARED, fd, 0);
    
       /* 공유 메모리 개체에 쓰기 */
       sprintf(ptr,"%s",message 0);
       ptr += strlen(message 0);
       sprintf(ptr,"%s",message 1);
       ptr += strlen(message 1);
    
       return 0;
       ##########################


       ######## 소비자 코드 ########
       /* 공유 메모리 개체 메모리에 매핑 */
       ptr = (char*) mmap(0, SIZE, PROT READ | PROT WRITE, MAP SHARED, fd, 0);
    
       /* 공유 메모리 개체로부터 읽기 */
       printf("%s",(char *)ptr);
    
       /* 공유 메모리 개체 지우기 */
       shm unlink(name);
    
       return 0;
       ##########################
   }
   ```

#### Pipes

- 두 개의 프로세스간 통신을 위한 수도관이라고 할 수 있다.
- 네가지 문제를 고려하여 구현한다.
   -  양방향 통신을 허용할지 단방향 통신을 할지
   - 양방향 통신이 가능하면 반이중 통신방식인지 전이중 통식방식인지
   - 통신할 프로세스 간 관계(부모-자식 관계 같은)가 반드시 존재하는지
   - 파이프가 다른 네트워크에서도 통신이 가능한지.

**Comment by lee-ji-hoon** [comment]
## IPC에 대해서 설명해주세요
> IPC는 프로세스 간 통신이며, 프로세스들끼리 서로 데이터를 주고 받는 행위 그에 대한 방법을 뜻합니다.  

![image](https://user-images.githubusercontent.com/53300830/183046291-3c14dffe-74df-4dfe-b1d8-5de23071a85f.png)
- 위 그림처럼 프로세스는 완전히 독립적인 실행객체로써 다른 프로세스의 영향을 받지 않습니다.  
- 독립돼 있는 만큼 별도의 설비가 없어 서로간의 통신이 어려워 ,커널 영역에서 IPC 라는 내부 프로세스간 통신을 제공하여 프로세스는 커널이 제공하는 IPC 설비를 이용해서 프로세스 간 통신을 하게 해줍니다.

### IPC의 종류 - Message Passing(메시지 전달)
- 커널이 제공하는 API를 이용해서 커널 공간을 통해 통신합니다. 
- 메시지 큐(Mesage Queue)를 사용하여 송신 프로세스는 큐에 enqueue, 수신 프로세스는 큐에 dequeue 하며 상호간 통신합니다.  

### IPC의 종류 - Shared Passing(메모리 공유)
- 프로세스끼리 특정 공통의 메모리 영역을 공유하며, 상호간 통신하는 방법입니다.
- 데이터 자체를 공유하도록 지원하며, 한 프로세스에서 변경한 메모리 공간의 내용을 다른 프로세스에서 접근할 수 있습니다.

두 개 모두 커널에서 관리가 됩니다.

## 파이프는 무엇일까요?
> 두 프로세스가 통신할수있게 하는 전달자역할을 하는 것을 파이프라고 합니다.
- IPC 통신과는 달리 한 방향으로만 통신이 가능합니다.
- 파이프 자체는 fork 함수에 의해 복사되지가 않는다고 합니다.

![image](https://user-images.githubusercontent.com/53300830/183093867-4f65aebf-ad25-482f-85a7-045a08a07ab4.png)
> 단 양방향 통신을 구현하게 될 경우 위처럼 파이프를 두 개를 생성해서 구현을 하게 됩니다.  
이때 양방향 통신을할때 반이중을 할지 전이중 통신방식으로 구현할지 고민을 해봐야합니다.

**Comment by this-is-spear** [comment]
### 프로세스 간 통신

기본적으로 프로세스는 자신에게 할당된 메모리에만 접근 가능하기 때문에 협동 프로세스들 간에는 통신 기법이 필요하다.

### 프로세스 간 통신 방법

- **공유 메모리(Shared Memory)**
    - 직접 접근
    - 빠른 속도와 편이성 제공
- **메시지 전달(Message Passing)**
    - 커널의 중개
    - 적은 양의 자료 교환에 유용

**공유 메모리**

공유 메모리는 두 개의 프로세스 안에 서로 공유할 수 있는 메모리이다. 시스템 호출로 등록되어진 메모리에 한에서 다른 프로세스들이 데이터를 읽을 수 있다. 데이터를 만들 때는 커널의 도움이 필요하지만 읽을 때는 사용자의 모드로 읽을 수 있다.

**공유 메모리 시스템**

서로 통신하려는 프로세스 간 공유 메모리 영역을 구축한다. 각 프로세스는 이 영역을 자신의 주소 공간에 추가하고 접근한다.

**접근 방법**
    - 공유 메모리에 기록되는 자료의 형식이나 위치는 프로세스들에 의해 결졍된다.
    - 동시에 동일한 위치에 쓰지 않도록 주의해야 한다.

**메시지 전달**

필요한 데이터를 직접적으로 가져오는 게 아닌 커널을 통해 메시지를 주고 받는다.

**신호**

한 프로세스에게 어떤 상황의 발생을 비동기적으로 알리는 방법이다. 한 프로세스가 다른 프로세스에게 알리거나 커널이 특정 프로세스에게 알리게 된다. 현재 프로세스 내외부에서 예상치 못하게 발생하는 비동기적 사건을 처리하기 위한 방법이다. 신호의 전달은 커널에 의해 이뤄진다.

> 💡 가장 오래된 IPC 방법이다.

**파이프**

프로세스간에 데이터를 전달하는 방법이다. 전송되는 데이터의 읽기 쓰기 위치를 임의로 변경할 수 없다. 그리고 순차적으로 읽고 사용해야 한다. 시스템 호출을 통해 커널 공간에 생성된 파이프를 통해 전달한다.
